### ISSUE TITLE
Volume Limit

### ISSUE THREAD

**Issue by blackjid** [ol-iver/denonavr#200]
It is possible somehow to set the volume limit via this integration?

My use case is that I want to make sure the limit is 60 all the time so my kid to instantly go all the way up with the volume.
But when I watch a movie, I want to override the limit for some time. Then automatically go back the child proof limit.

Thanks

**Comment by ol-iver** [comment]
How are you using this library? If you use a tool like Home Assistant that would be the right place to model rules like the volume limit in my opinion.

**Comment by blackjid** [comment]
Yes I'm using it on home assistant.
What do you mean by the right place to model volume limit?

I plan to use HA to create my automation to change the limit beard on different scenarios, but I need to know what command to send to the avr.

I was trying to find the right command to send to my receiver to set the limit, but I wasn't able to find it.

**Comment by ol-iver** [comment]
You are looking for a hardware limit, now I got it.

You can set it via web interface, but this is embedded into the setup page and does not look like a good programming interface. I really don't know if they look the same for different receivers and they are not supported by this library.

However, I am able to set limits using curl. Maybe the commands are working for you too and you could use something like [Command line Switch](https://www.home-assistant.io/integrations/switch.command_line/) integration in HA to make the calls.
These are my calls for Main Zone:

Limit off
```
curl "http://{{ receiverIP }}/SETUP/AUDIO/VOLUME/s_audio.asp" -H "Content-Type: application/x-www-form-urlencoded" -H "Cookie: ZoneName=MAIN"%"20ZONE" --data-raw "radioMainVolLimit=OFF"
```
Limit 80
```
curl "http://{{ receiverIP }}/SETUP/AUDIO/VOLUME/s_audio.asp" -H "Content-Type: application/x-www-form-urlencoded" -H "Cookie: ZoneName=MAIN"%"20ZONE" --data-raw "radioMainVolLimit=0dB"
```
Limit 70
```
curl "http://{{ receiverIP }}/SETUP/AUDIO/VOLUME/s_audio.asp" -H "Content-Type: application/x-www-form-urlencoded" -H "Cookie: ZoneName=MAIN"%"20ZONE" --data-raw "radioMainVolLimit=-10dB"
```
Limit 60
```
curl "http://{{ receiverIP }}/SETUP/AUDIO/VOLUME/s_audio.asp" -H "Content-Type: application/x-www-form-urlencoded" -H "Cookie: ZoneName=MAIN"%"20ZONE" --data-raw "radioMainVolLimit=-20dB"
```

**Comment by blackjid** [comment]
oh! thanks @scarface-4711 the curl commands did worked perfectly.... and the command line switch also :)

```
switch:
  - platform: command_line
    switches:
      receiver_volume_limit:
        command_on: '/usr/bin/curl "http://10.0.2.13/SETUP/AUDIO/VOLUME/s_audio.asp" -H "Content-Type: application/x-www-form-urlencoded" -H "Cookie: ZoneName=MAIN"%"20ZONE" --data-raw "radioMainVolLimit=-10dB"'
        command_off: '/usr/bin/curl "http://10.0.2.13/SETUP/AUDIO/VOLUME/s_audio.asp" -H "Content-Type: application/x-www-form-urlencoded" -H "Cookie: ZoneName=MAIN"%"20ZONE" --data-raw "radioMainVolLimit=OFF"'
        command_state: '/usr/bin/curl -s "http://10.0.2.13/SETUP/AUDIO/VOLUME/d_audio.asp" -H "Cookie: ZoneName=MAIN"%"20ZONE" | grep radioMainVolLimit | tr "<INPUT" "\n<INPUT" | grep checked | cut -d ">" -f 2'
        value_template: '{{ value != "Off" }}'
        friendly_name: Receiver Volume Limit
```
